#!/bin/bash
# please install dnsmasq hostapd before using
# Check root user
if [ $UID != 0 ]; then
    echo "ERROR: Not root user?"
    exit 1
fi
ifconfig wlan0 down
ifconfig wlan0 192.168.5.1
ifconfig wlan0 up
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o usb0 -j MASQUERADE
iptables -A FORWARD -i usb0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o usb0 -j ACCEPT
service dnsmasq restart
sudo service dhcpcd restart
service hostapd restart
